### ISSUE TITLE
Always Config error: unable to open config file

### ISSUE THREAD

**Issue by 0xAAE** [ds-voix/VX-PBX#1]
I put the `xswitcher.conf` into `~/.config/xswitcher` dir.
Then, every time the xswitcher starts it complains `Config error: unable to open config file: open ~/.config/xswitcher/xswitcher.conf: no such file or directory`
 I tried using the supplied conf file as well as empty one, the result is always the same

**Comment by ds-voix** [comment]
Thanks a lot for report.
I'd fixed the default config path to "/etc/xswitcher/xswitcher.conf", because the current xswitcher is in fact system-wide.
* And yes, it could be the problem in multi-user environments. But that so, because of the elected design.

:exclamation: Please note that the most of config is currently unimplemented. "ActionKeys" is the only working part. I had no time since the spring lockdown. M.b., on Christmas holidays…
